<x-oc-layout :pageTitle="$evidence ? 'Edit Evidence #'.$evidence->evidence_id : 'Log Evidence'">
<div class="mx-auto max-w-4xl">@if($errors->any())<div class="mb-5 rounded-xl border border-rose-500/20 bg-rose-500/10 p-4 text-sm text-rose-300"><ul class="list-inside list-disc">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<section class="rounded-xl border border-hq-700 bg-hq-800 shadow-xl"><header class="border-b border-hq-700 px-6 py-4"><h2 class="font-semibold text-white">{{$evidence?'Update evidence details':'Log a new evidence item'}}</h2><p class="mt-1 text-xs text-gray-500">Evidence can only be attached to FIRs from your station.</p></header>
<form method="POST" action="{{$evidence?route('oc.evidence.update',$evidence):route('oc.evidence.store')}}" class="grid gap-5 p-6 sm:grid-cols-2">@csrf @if($evidence)@method('PUT')@endif
<label class="text-xs font-semibold text-gray-400 sm:col-span-2">Case / FIR<select name="case_id" required class="mt-2 h-11 w-full rounded-lg border border-hq-600 bg-hq-900 px-3 text-sm text-white"><option value="">Select case</option>@foreach($cases as $case)<option value="{{$case->case_id}}" @selected((string)old('case_id',$selectedCase)===(string)$case->case_id)>FIR #{{$case->case_id}} — {{$case->case_title}}</option>@endforeach</select></label>
<label class="text-xs font-semibold text-gray-400">Evidence type<input name="type" required maxlength="100" value="{{old('type',$evidence?->type)}}" placeholder="Weapon, Document, Digital..." class="mt-2 h-11 w-full rounded-lg border border-hq-600 bg-hq-900 px-3 text-sm text-white"></label>
<label class="text-xs font-semibold text-gray-400">Collected date<input type="date" name="collected_date" required value="{{old('collected_date',$evidence?->collected_date??now()->toDateString())}}" class="mt-2 h-11 w-full rounded-lg border border-hq-600 bg-hq-900 px-3 text-sm text-white"></label>
<label class="text-xs font-semibold text-gray-400 sm:col-span-2">Collecting officer<select name="officer_id" required class="mt-2 h-11 w-full rounded-lg border border-hq-600 bg-hq-900 px-3 text-sm text-white"><option value="">Select officer</option>@foreach($officers as $officer)<option value="{{$officer->officer_id}}" @selected((string)old('officer_id',$evidence?->officer_id)===(string)$officer->officer_id)>{{$officer->name}} &middot; {{$officer->badge_number}}</option>@endforeach</select></label>
<label class="text-xs font-semibold text-gray-400 sm:col-span-2">Description<textarea name="description" rows="4" maxlength="2000" class="mt-2 w-full rounded-lg border border-hq-600 bg-hq-900 p-3 text-sm text-white">{{old('description',$evidence?->description)}}</textarea></label>
<div class="flex justify-end gap-3 border-t border-hq-700 pt-5 sm:col-span-2"><a href="{{route('oc.evidence.index')}}" class="px-5 py-2.5 text-sm text-gray-400">Cancel</a><button class="rounded-lg bg-gold-500 px-5 py-2.5 text-sm font-bold text-hq-900">{{$evidence?'Save changes':'Log evidence'}}</button></div>
</form></section></div>
</x-oc-layout>
