<x-oc-layout pageTitle="Evidence Management">
<div class="mx-auto max-w-7xl space-y-6">
 @if(session('success'))<div class="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4 text-sm text-emerald-300">{{session('success')}}</div>@endif
 <section class="grid grid-cols-3 gap-4">@foreach([['Evidence items',$summary['total'],'sky'],['Evidence types',$summary['types'],'indigo'],['Cases with evidence',$summary['cases'],'emerald']] as [$label,$value,$tone])<div class="rounded-xl border border-hq-700 bg-hq-800 p-4"><p class="text-[9px] font-bold uppercase tracking-widest text-gray-500">{{$label}}</p><div class="mt-2 flex items-end justify-between"><p class="text-2xl font-extrabold text-white">{{$value}}</p><span class="h-2.5 w-2.5 rounded-full bg-{{$tone}}-400"></span></div></div>@endforeach</section>
 <section class="overflow-hidden rounded-xl border border-hq-700 bg-hq-800 shadow-xl"><header class="flex flex-col gap-3 border-b border-hq-700 p-4 sm:flex-row sm:justify-between"><form class="flex flex-1 gap-3"><input name="search" value="{{request('search')}}" placeholder="Search type or description" class="h-10 flex-1 rounded-lg border border-hq-600 bg-hq-900 px-3 text-sm text-white"><select name="case_id" class="h-10 max-w-[240px] rounded-lg border border-hq-600 bg-hq-900 px-3 text-sm text-gray-300"><option value="">All cases</option>@foreach($cases as $case)<option value="{{$case->case_id}}" @selected((string)request('case_id')===(string)$case->case_id)>FIR #{{$case->case_id}} — {{$case->case_title}}</option>@endforeach</select><button class="rounded-lg bg-hq-600 px-4 text-xs font-bold">Filter</button></form><a href="{{route('oc.evidence.create')}}" class="inline-flex h-10 items-center justify-center rounded-lg bg-gold-500 px-4 text-xs font-bold text-hq-900">Log evidence</a></header>
 <div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left"><thead><tr class="bg-hq-900/50 text-[9px] font-bold uppercase tracking-widest text-gray-600"><th class="px-5 py-3">Evidence</th><th class="px-4 py-3">Case</th><th class="px-4 py-3">Collected by</th><th class="px-4 py-3">Collected</th><th class="px-5 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-hq-700">
 @forelse($evidence as $item)<tr class="text-xs"><td class="px-5 py-3"><p class="font-semibold text-gray-200">{{$item->type}}</p><p class="mt-0.5 max-w-xs truncate text-[10px] text-gray-600">{{$item->description?:'No description'}}</p></td><td class="px-4 py-3"><a href="{{route('oc.cases.show',$item->case)}}" class="text-blue-400">FIR #{{$item->case_id}}</a><p class="mt-0.5 max-w-[180px] truncate text-[10px] text-gray-600">{{$item->case->case_title}}</p></td><td class="px-4 py-3 text-gray-500">{{$item->officer->name}}</td><td class="px-4 py-3 text-gray-500">{{date('d M Y',strtotime($item->collected_date))}}</td><td class="px-5 py-3 text-right"><a href="{{route('oc.evidence.edit',$item)}}" class="text-amber-400">Edit</a></td></tr>
 @empty<tr><td colspan="5" class="p-12 text-center text-sm text-gray-600">No evidence items found.</td></tr>@endforelse
 </tbody></table></div><div class="border-t border-hq-700 p-4">{{$evidence->links()}}</div></section>
</div>
</x-oc-layout>
