<x-oc-layout :pageTitle="'FIR #'.$case->case_id">
<div class="mx-auto max-w-6xl space-y-6">
    @if(session('success'))<div class="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4 text-sm text-emerald-300">{{session('success')}}</div>@endif
    <section class="rounded-xl border border-hq-700 bg-hq-800 p-6 shadow-xl"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><span class="rounded-full bg-sky-500/10 px-2.5 py-1 text-[10px] font-bold text-sky-400">{{$case->status}}</span><h2 class="mt-3 text-2xl font-bold text-white">{{$case->case_title}}</h2><p class="mt-2 text-sm text-gray-500">{{$case->station->name}} &middot; Filed {{date('d M Y',strtotime($case->date_filed))}}</p></div><a href="{{route('oc.cases.edit',$case)}}" class="rounded-lg bg-gold-500 px-4 py-2.5 text-xs font-bold text-hq-900">Edit case</a></div>
        <div class="mt-6 grid gap-4 border-t border-hq-700 pt-5 sm:grid-cols-4"><div><p class="text-[9px] uppercase tracking-widest text-gray-600">Investigator</p><p class="mt-1 text-sm text-gray-300">{{$case->officer?->name??'Unassigned'}}</p></div><div><p class="text-[9px] uppercase tracking-widest text-gray-600">Source</p><p class="mt-1 text-sm text-gray-300">{{$case->complaint_id?'Complaint #'.$case->complaint_id:'Direct FIR'}}</p></div><div><p class="text-[9px] uppercase tracking-widest text-gray-600">Linked criminals</p><p class="mt-1 text-sm text-gray-300">{{$case->criminals->count()}}</p></div><div><p class="text-[9px] uppercase tracking-widest text-gray-600">Evidence items</p><p class="mt-1 text-sm text-gray-300">{{$case->evidence->count()}}</p></div></div>
    </section>
    <section class="rounded-xl border border-hq-700 bg-hq-800 shadow-xl"><header class="flex items-center justify-between border-b border-hq-700 px-5 py-4"><div><h3 class="text-sm font-semibold text-white">Linked evidence</h3><p class="mt-1 text-[11px] text-gray-500">Evidence logged against this FIR</p></div><a href="{{route('oc.evidence.create',['case_id'=>$case->case_id])}}" class="rounded-lg bg-gold-500 px-3 py-2 text-xs font-bold text-hq-900">Log evidence</a></header><div class="divide-y divide-hq-700">@forelse($case->evidence as $item)<div class="flex items-center justify-between gap-4 p-4"><div><p class="text-sm font-semibold text-gray-200">{{$item->type}}</p><p class="mt-1 text-[11px] text-gray-500">{{$item->description?:'No description'}} &middot; Collected by {{$item->officer->name}}</p></div><a href="{{route('oc.evidence.edit',$item)}}" class="text-xs font-semibold text-amber-400">Edit</a></div>@empty<div class="p-8 text-center text-sm text-gray-600">No evidence linked to this case.</div>@endforelse</div></section>
    <section class="rounded-xl border border-hq-700 bg-hq-800 shadow-xl"><header class="border-b border-hq-700 px-5 py-4"><h3 class="text-sm font-semibold text-white">Case timeline / audit log</h3><p class="mt-1 text-[11px] text-gray-500">Permanent history of OC actions on this FIR</p></header><div class="p-5">
        @forelse($case->auditLogs as $log)<div class="relative border-l border-hq-600 pb-6 pl-6 last:pb-0"><span class="absolute -left-1.5 top-1 h-3 w-3 rounded-full border-2 border-hq-800 bg-blue-400"></span><div class="flex flex-col gap-1 sm:flex-row sm:justify-between"><p class="text-sm font-semibold text-gray-200">{{$log->action}}</p><time class="text-[10px] text-gray-600">{{$log->created_at->format('d M Y, h:i A')}}</time></div>@if($log->old_status!==$log->new_status)<p class="mt-1 text-[11px] text-amber-400">{{$log->old_status??'None'}} â†’ {{$log->new_status}}</p>@endif<p class="mt-2 text-xs text-gray-500">{{$log->details}}</p><p class="mt-1 text-[10px] text-gray-600">By {{$log->user?->name??'System'}}</p></div>@empty<div class="py-8 text-center text-sm text-gray-600">No audit entries yet.</div>@endforelse
    </div></section>
</div>
</x-oc-layout>


