<x-oc-layout pageTitle="Criminal Management">
<div class="mx-auto max-w-7xl space-y-6">
 @if(session('success'))<div class="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4 text-sm text-emerald-300">{{session('success')}}</div>@endif
 <section class="grid grid-cols-3 gap-4">@foreach([['Registry',$summary['total'],'sky'],['Wanted',$summary['wanted'],'rose'],['Linked locally',$summary['linked'],'indigo']] as [$label,$value,$tone])<div class="rounded-xl border border-hq-700 bg-hq-800 p-4"><p class="text-[9px] font-bold uppercase tracking-widest text-gray-500">{{$label}}</p><div class="mt-2 flex items-end justify-between"><p class="text-2xl font-extrabold text-white">{{$value}}</p><span class="h-2.5 w-2.5 rounded-full bg-{{$tone}}-400"></span></div></div>@endforeach</section>
 <section class="overflow-hidden rounded-xl border border-hq-700 bg-hq-800 shadow-xl">
  <header class="flex flex-col gap-3 border-b border-hq-700 p-4 sm:flex-row sm:justify-between"><form class="flex flex-1 gap-3"><input name="search" value="{{request('search')}}" placeholder="Search name, alias or NID" class="h-10 flex-1 rounded-lg border border-hq-600 bg-hq-900 px-3 text-sm text-white"><select name="wanted" class="h-10 rounded-lg border border-hq-600 bg-hq-900 px-3 text-sm text-gray-300"><option value="">All statuses</option><option value="yes" @selected(request('wanted')==='yes')>Wanted</option><option value="no" @selected(request('wanted')==='no')>Not wanted</option></select><button class="rounded-lg bg-hq-600 px-4 text-xs font-bold">Filter</button></form><a href="{{route('oc.criminals.create')}}" class="inline-flex h-10 items-center justify-center rounded-lg bg-gold-500 px-4 text-xs font-bold text-hq-900">Add criminal</a></header>
  <div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left"><thead><tr class="bg-hq-900/50 text-[9px] font-bold uppercase tracking-widest text-gray-600"><th class="px-5 py-3">Person</th><th class="px-4 py-3">NID</th><th class="px-4 py-3">Date of birth</th><th class="px-4 py-3">Cases</th><th class="px-4 py-3">Status</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-hq-700">
  @forelse($criminals as $criminal)<tr class="text-xs"><td class="px-5 py-3"><p class="font-semibold text-gray-200">{{$criminal->name}}</p><p class="text-[10px] text-gray-600">{{$criminal->alias?:'No alias'}}</p></td><td class="px-4 py-3 text-gray-500">{{$criminal->nid_number?:'—'}}</td><td class="px-4 py-3 text-gray-500">{{$criminal->date_of_birth?date('d M Y',strtotime($criminal->date_of_birth)):'—'}}</td><td class="px-4 py-3 text-gray-500">{{$criminal->cases_count}}</td><td class="px-4 py-3"><span class="rounded-full px-2 py-1 text-[10px] font-bold {{$criminal->wanted_status?'bg-rose-500/10 text-rose-400':'bg-emerald-500/10 text-emerald-400'}}">{{$criminal->wanted_status?'Wanted':'Not wanted'}}</span></td><td class="px-5 py-3 text-right"><a href="{{route('oc.criminals.show',$criminal)}}" class="mr-2 text-blue-400">Manage</a><a href="{{route('oc.criminals.edit',$criminal)}}" class="text-amber-400">Edit</a></td></tr>
  @empty<tr><td colspan="6" class="p-12 text-center text-sm text-gray-600">No criminal records found.</td></tr>@endforelse
  </tbody></table></div><div class="border-t border-hq-700 p-4">{{$criminals->links()}}</div>
 </section>
</div>
</x-oc-layout>
