<x-dynamic-component :component="$layout" :pageTitle="$pageTitle">
    @php
        $fmt = fn ($value, $withTime = false) => $value
            ? \Carbon\Carbon::parse($value)->format($withTime ? 'd M Y, h:i A' : 'd M Y')
            : 'Not available';
    @endphp
    <div class="mx-auto max-w-6xl space-y-6">
        <div class="flex flex-wrap items-center justify-between gap-3">
            <a href="{{ $backUrl }}" class="inline-flex items-center rounded-lg border border-hq-600 px-4 py-2 text-xs font-semibold text-gray-400 transition hover:border-hq-500 hover:text-white">&larr; {{ $backLabel }}</a>
            @if(!empty($editUrl))
                <a href="{{ $editUrl }}" class="rounded-lg border border-gold-500/40 px-4 py-2 text-xs font-bold text-gold-400 transition hover:bg-gold-500/10">Edit record</a>
            @endif
        </div>

        @if($type === 'case')
            <section class="relative overflow-hidden rounded-xl border border-hq-700 bg-gradient-to-br from-hq-800 to-hq-700/60 p-6">
                <div class="absolute right-0 top-0 h-36 w-36 rounded-bl-full bg-sky-500/5"></div>
                <div class="relative flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between">
                    <div><p class="text-[10px] font-bold uppercase tracking-[.2em] text-sky-400">FIR #{{ $record->case_id }}</p><h2 class="mt-2 text-2xl font-bold text-white">{{ $record->case_title }}</h2><p class="mt-2 text-sm text-gray-500">{{ $record->station_name }} · {{ $record->command_name ?: 'Command HQ unavailable' }}</p></div>
                    <span class="rounded-full border border-amber-500/20 bg-amber-500/10 px-3 py-1.5 text-xs font-bold text-amber-400">{{ $record->status }}</span>
                </div>
                <dl class="relative mt-6 grid gap-4 border-t border-hq-700 pt-5 sm:grid-cols-4">
                    <div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Investigator</dt><dd class="mt-1 text-sm text-gray-300">{{ $record->officer_name ?: 'Unassigned' }}</dd></div>
                    <div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Filed</dt><dd class="mt-1 text-sm text-gray-300">{{ $fmt($record->date_filed) }}</dd></div>
                    <div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Source</dt><dd class="mt-1 text-sm text-gray-300">{{ $record->complaint_id ? 'Complaint #'.$record->complaint_id : 'Direct FIR' }}</dd></div>
                    <div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Linked records</dt><dd class="mt-1 text-sm text-gray-300">{{ $criminals->count() }} criminals · {{ $evidence->count() }} evidence</dd></div>
                </dl>
            </section>

            <div class="grid gap-6 lg:grid-cols-2">
                <section class="overflow-hidden rounded-xl border border-hq-700 bg-hq-800"><header class="border-b border-hq-700 px-5 py-4"><h3 class="font-semibold text-white">Linked criminals</h3><p class="mt-1 text-xs text-gray-500">Every person linked to this FIR and their involvement</p></header><div class="divide-y divide-hq-700/60">@forelse($criminals as $item)<div class="flex items-center justify-between gap-4 p-4"><div><p class="font-semibold text-gray-200">{{ $item->name }}</p><p class="mt-1 text-xs text-gray-600">{{ $item->alias ?: 'No alias' }}</p></div><span class="text-xs font-semibold text-sky-400">{{ $item->involvement_type }}</span></div>@empty<div class="p-10 text-center text-sm text-gray-600">No criminals linked.</div>@endforelse</div></section>
                <section class="overflow-hidden rounded-xl border border-hq-700 bg-hq-800"><header class="border-b border-hq-700 px-5 py-4"><h3 class="font-semibold text-white">Evidence register</h3><p class="mt-1 text-xs text-gray-500">Items collected for this FIR</p></header><div class="divide-y divide-hq-700/60">@forelse($evidence as $item)<div class="p-4"><div class="flex justify-between gap-4"><p class="font-semibold text-gray-200">{{ $item->type }}</p><time class="text-xs text-gray-600">{{ $fmt($item->collected_date) }}</time></div><p class="mt-1 text-xs text-gray-500">{{ $item->description ?: 'No description' }}</p><p class="mt-2 text-[10px] text-gray-600">Collected by {{ $item->officer_name ?: 'Unknown officer' }}</p></div>@empty<div class="p-10 text-center text-sm text-gray-600">No evidence logged.</div>@endforelse</div></section>
            </div>

            <section class="overflow-hidden rounded-xl border border-hq-700 bg-hq-800"><header class="border-b border-hq-700 px-5 py-4"><h3 class="font-semibold text-white">Case timeline / audit log</h3></header><div class="p-5">@forelse($auditLogs as $log)<div class="relative border-l border-hq-600 pb-6 pl-6 last:pb-0"><span class="absolute -left-1.5 top-1 h-3 w-3 rounded-full border-2 border-hq-800 bg-sky-400"></span><div class="flex flex-wrap justify-between gap-2"><p class="text-sm font-semibold text-gray-200">{{ $log->action }}</p><time class="text-[10px] text-gray-600">{{ $fmt($log->created_at, true) }}</time></div>@if($log->old_status !== $log->new_status)<p class="mt-1 text-xs text-amber-400">{{ $log->old_status ?: 'None' }} → {{ $log->new_status ?: 'None' }}</p>@endif<p class="mt-2 text-xs text-gray-500">{{ $log->details }}</p><p class="mt-1 text-[10px] text-gray-600">By {{ $log->user_name ?: 'System' }}</p></div>@empty<div class="py-8 text-center text-sm text-gray-600">No audit entries yet.</div>@endforelse</div></section>
        @elseif($type === 'criminal')
            <section class="relative overflow-hidden rounded-xl border border-hq-700 bg-gradient-to-br from-hq-800 to-hq-700/60 p-6">
                <div class="absolute right-0 top-0 h-36 w-36 rounded-bl-full {{ $record->wanted_status ? 'bg-rose-500/10' : 'bg-emerald-500/5' }}"></div>
                <div class="relative flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-[10px] font-bold uppercase tracking-[.2em] text-indigo-400">Criminal registry #{{ $record->criminal_id }}</p><h2 class="mt-2 text-2xl font-bold text-white">{{ $record->name }}</h2><p class="mt-2 text-sm text-gray-500">{{ $record->alias ?: 'No known alias' }}</p></div><span class="{{ $record->wanted_status ? 'text-rose-400 border-rose-500/20 bg-rose-500/10' : 'text-emerald-400 border-emerald-500/20 bg-emerald-500/10' }} rounded-full border px-3 py-1.5 text-xs font-bold">{{ $record->wanted_status ? 'Wanted' : 'Not wanted' }}</span></div>
                <dl class="relative mt-6 grid gap-4 border-t border-hq-700 pt-5 sm:grid-cols-3"><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">NID</dt><dd class="mt-1 text-sm text-gray-300">{{ $record->nid_number ?: 'Not recorded' }}</dd></div><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Date of birth</dt><dd class="mt-1 text-sm text-gray-300">{{ $fmt($record->date_of_birth) }}</dd></div><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Visible FIR links</dt><dd class="mt-1 text-sm text-gray-300">{{ $relatedCases->count() }}</dd></div></dl>
            </section>
            <section class="overflow-hidden rounded-xl border border-hq-700 bg-hq-800"><header class="border-b border-hq-700 px-5 py-4"><h3 class="font-semibold text-white">Linked FIR history</h3><p class="mt-1 text-xs text-gray-500">The same person can appear in multiple cases; each relationship is shown separately.</p></header><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left text-sm"><thead class="bg-hq-900/60 text-[10px] uppercase tracking-widest text-gray-500"><tr><th class="px-5 py-4">FIR</th><th class="px-4 py-4">Thana</th><th class="px-4 py-4">Involvement</th><th class="px-4 py-4">Investigator</th><th class="px-4 py-4">Filed</th><th class="px-5 py-4 text-right">Status</th></tr></thead><tbody class="divide-y divide-hq-700/60">@forelse($relatedCases as $case)<tr><td class="px-5 py-4"><p class="font-semibold text-gray-200">{{ $case->case_title }}</p><p class="mt-1 text-xs text-gray-600">#{{ $case->case_id }}</p></td><td class="px-4 py-4 text-gray-500">{{ $case->station_name }}</td><td class="px-4 py-4 font-semibold text-sky-400">{{ $case->involvement_type }}</td><td class="px-4 py-4 text-gray-500">{{ $case->officer_name ?: 'Unassigned' }}</td><td class="px-4 py-4 text-gray-500">{{ $fmt($case->date_filed) }}</td><td class="px-5 py-4 text-right text-amber-400">{{ $case->status }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-gray-600">No FIR links visible in this jurisdiction.</td></tr>@endforelse</tbody></table></div></section>
        @elseif($type === 'complaint')
            <section class="relative overflow-hidden rounded-xl border border-hq-700 bg-gradient-to-br from-hq-800 to-hq-700/60 p-6"><div class="absolute right-0 top-0 h-36 w-36 rounded-bl-full bg-yellow-500/5"></div><div class="relative flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-[10px] font-bold uppercase tracking-[.2em] text-yellow-400">Complaint #{{ $record->complaint_id }}</p><h2 class="mt-2 text-2xl font-bold text-white">{{ $record->complainant_name }}</h2><p class="mt-2 text-sm text-gray-500">{{ $record->station_name }} · {{ $record->command_name ?: 'Command HQ unavailable' }}</p></div><span class="rounded-full border border-yellow-500/20 bg-yellow-500/10 px-3 py-1.5 text-xs font-bold text-yellow-400">{{ $record->status }}</span></div><dl class="relative mt-6 grid gap-4 border-t border-hq-700 pt-5 sm:grid-cols-3"><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Submitted</dt><dd class="mt-1 text-sm text-gray-300">{{ $fmt($record->submitted_date) }}</dd></div><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Complainant NID</dt><dd class="mt-1 text-sm text-gray-300">{{ $record->complainant_nid ?: 'Not recorded' }}</dd></div><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">FIR conversion</dt><dd class="mt-1 text-sm text-gray-300">{{ $linkedCase ? '#'.$linkedCase->case_id : 'Not converted' }}</dd></div></dl></section>
            <section class="rounded-xl border border-hq-700 bg-hq-800 p-6"><h3 class="font-semibold text-white">Incident description</h3><p class="mt-4 whitespace-pre-line text-sm leading-7 text-gray-400">{{ $record->description }}</p></section>
            <section class="grid gap-6 lg:grid-cols-2"><article class="rounded-xl border border-hq-700 bg-hq-800 p-5"><h3 class="font-semibold text-white">Complaint activity</h3><div class="mt-5 space-y-5"><div class="border-l border-hq-600 pl-5"><p class="text-sm font-semibold text-gray-200">Complaint submitted</p><p class="mt-1 text-xs text-gray-600">{{ $fmt($record->submitted_date, true) }}</p></div><div class="border-l border-sky-500/50 pl-5"><p class="text-sm font-semibold text-gray-200">Current status: {{ $record->status }}</p><p class="mt-1 text-xs text-gray-600">Latest workflow state</p></div>@if($linkedCase)<div class="border-l border-emerald-500/50 pl-5"><p class="text-sm font-semibold text-emerald-400">Converted to FIR #{{ $linkedCase->case_id }}</p><p class="mt-1 text-xs text-gray-600">{{ $linkedCase->case_title }}</p></div>@endif</div></article><article class="rounded-xl border border-hq-700 bg-hq-800 p-5"><h3 class="font-semibold text-white">Linked FIR</h3>@if($linkedCase)<dl class="mt-5 space-y-4 text-sm"><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Title</dt><dd class="mt-1 text-gray-300">{{ $linkedCase->case_title }}</dd></div><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Investigator</dt><dd class="mt-1 text-gray-300">{{ $linkedCase->officer_name ?: 'Unassigned' }}</dd></div><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Status</dt><dd class="mt-1 text-amber-400">{{ $linkedCase->status }}</dd></div></dl>@else<p class="mt-5 text-sm text-gray-600">This complaint has not been escalated to an FIR.</p>@endif</article></section>
        @else
            <section class="relative overflow-hidden rounded-xl border border-hq-700 bg-gradient-to-br from-hq-800 to-hq-700/60 p-6"><div class="absolute right-0 top-0 h-36 w-36 rounded-bl-full bg-indigo-500/5"></div><div class="relative flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-[10px] font-bold uppercase tracking-[.2em] text-indigo-400">Officer profile #{{ $record->officer_id }}</p><h2 class="mt-2 text-2xl font-bold text-white">{{ $record->name }}</h2><p class="mt-2 text-sm text-gray-500">{{ $record->rank }} · {{ $record->badge_number }}</p></div><div class="flex gap-2">@if($record->is_oc)<span class="rounded-full border border-gold-500/20 bg-gold-500/10 px-3 py-1.5 text-xs font-bold text-gold-400">Officer in Charge</span>@endif<span class="rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1.5 text-xs font-bold text-emerald-400">{{ $record->status }}</span></div></div><dl class="relative mt-6 grid gap-4 border-t border-hq-700 pt-5 sm:grid-cols-3"><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Station</dt><dd class="mt-1 text-sm text-gray-300">{{ $record->station_name }}</dd></div><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Assigned FIRs</dt><dd class="mt-1 text-2xl font-bold text-white">{{ $relatedCases->count() }}</dd></div><div><dt class="text-[9px] uppercase tracking-widest text-gray-600">Evidence logged</dt><dd class="mt-1 text-2xl font-bold text-white">{{ $evidence->count() }}</dd></div></dl></section>
            <div class="grid gap-6 lg:grid-cols-2"><section class="overflow-hidden rounded-xl border border-hq-700 bg-hq-800"><header class="border-b border-hq-700 px-5 py-4"><h3 class="font-semibold text-white">Assigned FIRs</h3></header><div class="divide-y divide-hq-700/60">@forelse($relatedCases as $case)<div class="p-4"><div class="flex justify-between gap-3"><p class="font-semibold text-gray-200">{{ $case->case_title }}</p><span class="text-xs text-amber-400">{{ $case->status }}</span></div><p class="mt-1 text-xs text-gray-600">FIR #{{ $case->case_id }} · {{ $fmt($case->date_filed) }}</p></div>@empty<div class="p-10 text-center text-sm text-gray-600">No assigned FIRs.</div>@endforelse</div></section><section class="overflow-hidden rounded-xl border border-hq-700 bg-hq-800"><header class="border-b border-hq-700 px-5 py-4"><h3 class="font-semibold text-white">Evidence collected</h3></header><div class="divide-y divide-hq-700/60">@forelse($evidence as $item)<div class="p-4"><p class="font-semibold text-gray-200">{{ $item->type }}</p><p class="mt-1 text-xs text-gray-600">FIR #{{ $item->case_id }} · {{ $fmt($item->collected_date) }}</p></div>@empty<div class="p-10 text-center text-sm text-gray-600">No evidence logged.</div>@endforelse</div></section></div>
        @endif
    </div>
</x-dynamic-component>
