<x-admin-layout pageTitle="{{ $station->name }} Criminal Dictionary">
    <div class="mx-auto max-w-[1440px] space-y-6">
        <section class="relative overflow-hidden rounded-xl border border-hq-700 bg-gradient-to-br from-hq-800 via-hq-800 to-hq-700/70 p-5 shadow-xl shadow-black/10 sm:p-6">
            <div class="absolute -right-20 -top-20 h-56 w-56 rounded-full bg-rose-500/10 blur-3xl"></div>
            <div class="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
                <div class="max-w-3xl"><div class="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-rose-400"><span class="h-1.5 w-1.5 rounded-full bg-rose-400"></span>{{ $station->parent?->name ?? 'Station command' }}</div><h2 class="text-2xl font-bold tracking-tight text-white">{{ $station->name }} criminal dictionary</h2><p class="mt-2 text-sm leading-6 text-gray-400">Criminals linked to FIRs under this thana only.</p></div>
                <div class="flex flex-wrap gap-3">@if($station->parent)<a href="{{ route('admin.criminals.hq', $station->parent->station_id) }}" class="inline-flex items-center justify-center rounded-lg border border-hq-600 bg-transparent px-4 py-2.5 text-sm font-bold text-gray-300 transition hover:bg-gold-500/10">Back to {{ $station->parent->name }}</a>@endif<a href="{{ route('admin.criminals.index') }}" class="inline-flex items-center justify-center rounded-lg border border-gold-500/40 bg-transparent px-4 py-2.5 text-sm font-bold text-gold-400 transition hover:bg-gold-500/10">Criminal browser</a></div>
            </div>
        </section>
        <section class="grid grid-cols-2 gap-4 xl:grid-cols-4">@foreach ([['Criminals',$summary['total'],'Linked here','rose'],['Wanted',$summary['wanted'],'Active wanted status','amber'],['FIRs',$summary['cases'],'Local case files','sky'],['FIRs with criminals',$summary['linked_cases'],'Linked case files','indigo']] as [$label,$value,$note,$color])<div class="group relative overflow-hidden rounded-xl border border-hq-700 bg-hq-800 p-5 transition hover:border-{{ $color }}-500/40"><div class="absolute right-0 top-0 h-20 w-20 rounded-bl-full bg-{{ $color }}-500/5"></div><p class="relative text-xs font-bold uppercase tracking-widest text-gray-500">{{ $label }}</p><p class="relative mt-2 text-3xl font-extrabold text-white">{{ number_format($value) }}</p><p class="relative mt-4 text-xs text-gray-500">{{ $note }}</p></div>@endforeach</section>
        <section class="overflow-hidden rounded-xl border border-hq-700 bg-hq-800 shadow-xl shadow-black/5"><div class="flex flex-col gap-3 border-b border-hq-700 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="text-base font-semibold text-white">Criminal dictionary</h3><p class="mt-1 text-xs text-gray-500">Search and filter linked criminals for this station.</p></div><span class="w-fit rounded-full border border-hq-600 bg-hq-900/60 px-3 py-1 text-xs font-bold uppercase tracking-wider text-gray-400">{{ $criminals->total() }} records</span></div>@include('admin.criminals.partials.criminal-table', ['showStation' => false])</section>
    </div>
</x-admin-layout>
